export const INSTRUCTIONS = `Eres un asistente virtual que ha sido diseñado para brindar información acerca de la escuela académica de Ingeniería de Sistemas de la Universidad Nacional de Trujillo. Proporcione únicamente información que se encuentre en los datos de la escuela académica proporcionados acontinuación. Si la respuesta no se encuentra en los datos de la escuela académica, responda con un mensaje indicando que no tiene información al respecto. Además no confundas los terminos ciclo con semestre, no son lo mismo. Algunos ciclos académicos de una misma carrera se imparten simultáneamente en un periodo o semestre académico.  Si la pregunta es ambigua o no está clara, solicite al usuario que proporcione más detalles para que pueda proporcionar una respuesta precisa. Si no está seguro de la respuesta, solicite al usuario que proporcione más información para que pueda investigar y brindar una respuesta precisa. Por cierto la fecha actual es ${new Date().toLocaleDateString()}. NO INVENTES NOMBRES, ENLACES, FECHAS, ETC.`;

export const GREETING = "Hola, soy un asistente virtual que ha sido diseñado para brindar información acerca de la escuela académica de Ingeniería de Sistemas de la Universidad Nacional de Trujillo. ¿En qué puedo ayudarte?"

export const THANKS = "¡De nada! Si tiene alguna otra pregunta, no dude en preguntar. Estoy aquí para ayudarlo."

export const THANKS_PHRASES = [
    'gracias',
    'cool',
    'genial',
    'asombroso',
    'muy util',
    'bien',
    'bueno',
    'excelente',
    'perfecto',
]

export const KEYWORDS = ["asignaturas", "profesores",
    "docentes", "cursos", "ciclos", "semestres",
    "1", "2", "3", "4", "5", "6", "7", "8", "9", "10",
    "primero", "segundo", "tercero", "cuarto", "quinto", "sexto",
    "primer", "segundo", "tercer", "cuarto", "quinto", "sexto",
    "septimo", "octavo", "noveno", "decimo",
    "ciclo",
    "semestre",
    "1er", "2do", "3er", "4to", "5to", "6to", "7mo", "8vo", "9no", "10mo", "docente", "profesor", "enseña", "conoces a", "conoces de", "conoces",
    "curso", "dicta", "dictan", "imparte", "imparten", "director"
]

export const FAQ_KEYWORDS: string[] = [
    "secretaría",
    "secretaria",
    "numero secretaria",
    "número secretaria",
    "teléfono",
    "whatsapp",
    "numero",
    "telefono",
    "correo",
    "horario",
    "atencion",
    "ingeniería",
    "sistemas",
    "horario",
    "atención",
    "contacto",
    "matrícula",
    "suv",
    "sistema",
    "universitario",
    "virtual",
    "orden",
    "pago",
    "agente",
    "interbank",
    "código",
    "servicio",
    "regularización",
    "ficha",
    "manual",
    "formato",
    "único",
    "trámite",
    "fut",
    "prácticas",
    "carnet",
    "trabajo",
    "suficiencia",
    "profesional",
    "biblioteca",
    "trámites",
    "enlace",
    "matricular",
    "registro",
    "inscripción",
    "inscribir",
    "inscribirme",
    "matricularme",
    "regularizar",
    "pagar",
    "pago",
    "susti",
    "sustis",
    "sustitutorio",
    "recuperación",
    "recuperacion",
    "aplazado",
    "aplazados",
    "bienestar",
    "beca",
    "becas",
    "becado",
    "comedores",
    "comedor",
    "requisitos",
    "requisito",
    "plazos",
    "plazo",
    "convocatoria",
    "convocatorias",
    "gimnasios",
    "gimnasio",
    "gym",
    "deporte",
    "taller",
    "talleres",
    "técnico",
    "tecnico",
    "fútbol",
    "futbol",
    "vóley",
    "voley",
    "básquet",
    "basquet",
    "básquetbol",
    "basquetbol",
    "básquetball",
    "basquetball",
    "FUT",
    "reprobar",
    "jalar",
    "jalo",
    "repruebo",
    "apruebo",
    "jalé",
    "reprobé",
    "aprobé",
    "reprobado",
    "aprobado",
    "reprobada",
    "aprobada",
    "reprobados",
    "aprobados",
    "teoría",
    "teoria",
    "laboratorio",
    "laboratorios",
    "lab",
    "labs",
    "aulas",
    "aula",
    "donde son las clases",
"nota","mínima","notas","mínimo","mínimas","mínimos","minima","minimo","minimas","minimos","puntaje",
];
